import { Skill } from "./types";

export const skills: Skill[] = [
  {
    id: "react",
    name: "React",
    icon: "react",
    category: "Frontend",
    level: "Advanced",
    proficiency: 92,
    experience: "2+ Years",
    description:
      "Built reusable components, dashboards, responsive interfaces and animations.",
    projects: ["Portfolio", "Employee Task Manager", "Internship Projects"],
    related: ["next", "typescript"],
  },

  {
    id: "next",
    name: "Next.js",
    icon: "next",
    category: "Frontend",
    level: "Advanced",
    proficiency: 86,
    experience: "1+ Year",
    description:
      "Built production-ready applications using App Router and Server Components.",
    projects: ["Portfolio"],
    related: ["react", "typescript"],
  },

  {
    id: "typescript",
    name: "TypeScript",
    icon: "typescript",
    category: "Languages",
    level: "Strong",
    proficiency: 80,
    experience: "1+ Year",
    description: "Used throughout modern React and Next.js projects.",
    projects: ["Portfolio"],
    related: ["react", "next"],
  },

  {
    id: "node",
    name: "Node.js",
    icon: "node",
    category: "Backend",
    level: "Strong",
    proficiency: 78,
    experience: "2 Years",
    description: "REST APIs, authentication and backend services.",
    projects: ["Task Manager"],
    related: ["mongodb", "docker"],
  },

  {
    id: "mongodb",
    name: "MongoDB",
    icon: "mongodb",
    category: "Database",
    level: "Strong",
    proficiency: 74,
    experience: "2 Years",
    description: "Database design and backend integration.",
    projects: ["Task Manager"],
    related: ["node"],
  },

  {
    id: "docker",
    name: "Docker",
    icon: "docker",
    category: "DevOps",
    level: "Comfortable",
    proficiency: 62,
    experience: "1 Year",
    description: "Containerization and deployment workflows.",
    projects: ["DevOps Internship"],
    related: ["linux"],
  },

  {
    id: "linux",
    name: "Linux",
    icon: "linux",
    category: "DevOps",
    level: "Comfortable",
    proficiency: 60,
    experience: "1 Year",
    description: "Server management and DevOps workflows.",
    projects: ["DevOps Internship"],
    related: ["docker"],
  },

  {
    id: "unity",
    name: "Unity",
    icon: "unity",
    category: "Game Development",
    level: "Strong",
    proficiency: 88,
    experience: "3 Years",
    description: "Gameplay programming, XR, AI and animation systems.",
    projects: ["Kitchen Carnage", "VR Robot", "Forest Project"],
    related: ["csharp"],
  },

  {
    id: "csharp",
    name: "C#",
    icon: "csharp",
    category: "Languages",
    level: "Strong",
    proficiency: 84,
    experience: "3 Years",
    description: "Primary language for Unity development.",
    projects: ["Kitchen Carnage", "VR Robot"],
    related: ["unity"],
  },

  // ---- Languages ----
  {
    id: "javascript",
    name: "JavaScript",
    icon: "javascript",
    category: "Languages",
    level: "Advanced",
    proficiency: 88,
    experience: "2+ Years",
    description: "Core language behind React, Next.js and Node.js work.",
    projects: ["Portfolio", "Employee Task Manager"],
    related: ["react", "node", "typescript"],
  },
  {
    id: "python",
    name: "Python",
    icon: "python",
    category: "Languages",
    level: "Strong",
    proficiency: 75,
    experience: "1+ Year",
    description: "Scripting, automation, backend APIs and AI/ML experiments.",
    projects: ["AI Projects"],
    related: ["django", "flask", "tensorflow", "pytorch"],
  },
  {
    id: "cpp",
    name: "C++",
    icon: "cpp",
    category: "Languages",
    level: "Comfortable",
    proficiency: 65,
    experience: "1 Year",
    description: "Performance-critical game logic and systems programming.",
    projects: ["Unreal Projects"],
    related: ["unreal", "unity"],
  },
  {
    id: "sql",
    name: "SQL",
    icon: "sql",
    category: "Languages",
    level: "Strong",
    proficiency: 78,
    experience: "1+ Year",
    description: "Relational schema design and querying for backend services.",
    projects: ["Task Manager"],
    related: ["postgresql", "mysql", "sqlite"],
  },

  // ---- Frontend ----
  {
    id: "html5",
    name: "HTML5",
    icon: "html5",
    category: "Frontend",
    level: "Advanced",
    proficiency: 90,
    experience: "2+ Years",
    description: "Semantic, accessible markup for every frontend project.",
    projects: ["Portfolio"],
    related: ["css3", "react"],
  },
  {
    id: "css3",
    name: "CSS3",
    icon: "css3",
    category: "Frontend",
    level: "Advanced",
    proficiency: 88,
    experience: "2+ Years",
    description: "Responsive layouts, animations and design systems.",
    projects: ["Portfolio"],
    related: ["html5", "tailwind"],
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    icon: "tailwind",
    category: "Frontend",
    level: "Advanced",
    proficiency: 85,
    experience: "1+ Year",
    description: "Utility-first styling for fast, consistent UI development.",
    projects: ["Portfolio"],
    related: ["react", "next"],
  },
  {
    id: "redux",
    name: "Redux",
    icon: "redux",
    category: "Frontend",
    level: "Comfortable",
    proficiency: 68,
    experience: "1 Year",
    description: "Predictable state management for larger React apps.",
    projects: ["Employee Task Manager"],
    related: ["react"],
  },

  // ---- Backend ----
  {
    id: "express",
    name: "Express.js",
    icon: "express",
    category: "Backend",
    level: "Strong",
    proficiency: 76,
    experience: "2 Years",
    description: "Lightweight REST APIs and middleware on top of Node.js.",
    projects: ["Task Manager"],
    related: ["node", "mongodb"],
  },
  {
    id: "django",
    name: "Django",
    icon: "django",
    category: "Backend",
    level: "Comfortable",
    proficiency: 60,
    experience: "1 Year",
    description: "Full-featured Python framework for rapid backend development.",
    projects: ["AI Projects"],
    related: ["python", "flask"],
  },
  {
    id: "flask",
    name: "Flask",
    icon: "flask",
    category: "Backend",
    level: "Comfortable",
    proficiency: 62,
    experience: "1 Year",
    description: "Lightweight Python APIs, often serving AI/ML models.",
    projects: ["AI Projects"],
    related: ["python", "django"],
  },
  {
    id: "graphql",
    name: "GraphQL",
    icon: "graphql",
    category: "Backend",
    level: "Comfortable",
    proficiency: 58,
    experience: "6+ Months",
    description: "Typed query layer for flexible client-driven APIs.",
    projects: ["Portfolio"],
    related: ["node", "express"],
  },

  // ---- Database ----
  {
    id: "postgresql",
    name: "PostgreSQL",
    icon: "postgresql",
    category: "Database",
    level: "Strong",
    proficiency: 74,
    experience: "1+ Year",
    description: "Relational database design, indexing and query optimization.",
    projects: ["Task Manager"],
    related: ["sql", "mysql"],
  },
  {
    id: "mysql",
    name: "MySQL",
    icon: "mysql",
    category: "Database",
    level: "Strong",
    proficiency: 72,
    experience: "1+ Year",
    description: "Relational database management for backend services.",
    projects: ["Task Manager"],
    related: ["sql", "postgresql"],
  },
  {
    id: "sqlite",
    name: "SQLite",
    icon: "sqlite",
    category: "Database",
    level: "Comfortable",
    proficiency: 65,
    experience: "1 Year",
    description: "Lightweight embedded database for prototypes and small apps.",
    projects: ["Internship Projects"],
    related: ["sql"],
  },
  {
    id: "redis",
    name: "Redis",
    icon: "redis",
    category: "Database",
    level: "Comfortable",
    proficiency: 58,
    experience: "6+ Months",
    description: "In-memory caching and session storage for faster backends.",
    projects: ["Task Manager"],
    related: ["node", "express"],
  },

  // ---- DevOps & Automation ----
  {
    id: "git",
    name: "Git",
    icon: "git",
    category: "DevOps",
    level: "Advanced",
    proficiency: 90,
    experience: "3 Years",
    description: "Version control and collaborative workflows across all projects.",
    projects: ["Portfolio", "Task Manager", "Kitchen Carnage"],
    related: ["linux", "githubactions"],
  },
  {
    id: "githubactions",
    name: "GitHub Actions",
    icon: "githubactions",
    category: "DevOps",
    level: "Comfortable",
    proficiency: 64,
    experience: "1 Year",
    description: "CI/CD pipelines for automated testing and deployment.",
    projects: ["DevOps Internship"],
    related: ["git", "docker"],
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    icon: "kubernetes",
    category: "DevOps",
    level: "Comfortable",
    proficiency: 55,
    experience: "6+ Months",
    description: "Container orchestration for scalable deployments.",
    projects: ["DevOps Internship"],
    related: ["docker", "linux"],
  },
  {
    id: "aws",
    name: "AWS",
    icon: "aws",
    category: "DevOps",
    level: "Comfortable",
    proficiency: 60,
    experience: "1 Year",
    description: "Cloud infrastructure, hosting and deployment automation.",
    projects: ["DevOps Internship"],
    related: ["docker", "linux"],
  },
  {
    id: "jenkins",
    name: "Jenkins",
    icon: "jenkins",
    category: "DevOps",
    level: "Comfortable",
    proficiency: 52,
    experience: "6+ Months",
    description: "Automated build and deployment pipelines.",
    projects: ["DevOps Internship"],
    related: ["git", "docker"],
  },

  // ---- AI ----
  {
    id: "tensorflow",
    name: "TensorFlow",
    icon: "tensorflow",
    category: "AI",
    level: "Comfortable",
    proficiency: 60,
    experience: "6+ Months",
    description: "Building and training neural network models.",
    projects: ["AI Projects"],
    related: ["python", "pytorch"],
  },
  {
    id: "pytorch",
    name: "PyTorch",
    icon: "pytorch",
    category: "AI",
    level: "Comfortable",
    proficiency: 60,
    experience: "6+ Months",
    description: "Deep learning research and model prototyping.",
    projects: ["AI Projects"],
    related: ["python", "tensorflow"],
  },
  {
    id: "openai",
    name: "OpenAI / LLM APIs",
    icon: "openai",
    category: "AI",
    level: "Strong",
    proficiency: 70,
    experience: "1 Year",
    description: "Integrating large language models into applications.",
    projects: ["AI Projects", "Portfolio"],
    related: ["python", "node"],
  },
  {
    id: "scikitlearn",
    name: "Scikit-learn",
    icon: "scikitlearn",
    category: "AI",
    level: "Comfortable",
    proficiency: 58,
    experience: "6+ Months",
    description: "Classical machine learning models and data pipelines.",
    projects: ["AI Projects"],
    related: ["python", "pandas"],
  },
  {
    id: "pandas",
    name: "Pandas",
    icon: "pandas",
    category: "AI",
    level: "Strong",
    proficiency: 68,
    experience: "1 Year",
    description: "Data wrangling and analysis for ML workflows.",
    projects: ["AI Projects"],
    related: ["python", "scikitlearn"],
  },

  // ---- Game Development ----
  {
    id: "unreal",
    name: "Unreal Engine",
    icon: "unreal",
    category: "Game Development",
    level: "Comfortable",
    proficiency: 55,
    experience: "6+ Months",
    description: "3D game development with Blueprints and C++.",
    projects: ["Unreal Projects"],
    related: ["cpp", "unity"],
  },
  {
    id: "blender",
    name: "Blender",
    icon: "blender",
    category: "Game Development",
    level: "Comfortable",
    proficiency: 60,
    experience: "1 Year",
    description: "3D modeling, texturing and asset creation for game projects.",
    projects: ["Kitchen Carnage", "Forest Project"],
    related: ["unity", "unreal"],
  },
];
